### ISSUE TITLE
Attribute Error for python 3.11

### ISSUE THREAD

**Issue by PhilipDeegan** [jupyter/jupyter_events#68]
Trying to start jupyterlab on python 3.11 I see the following 

```
AttributeError: module 'collections' has no attribute 'Hashable'
```

whole stack

```
python3 -m jupyterlab
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/opt/py/py/lib/python3.11/site-packages/jupyterlab/__init__.py", line 7, in <module>
    from .handlers.announcements import (  # noqa
  File "/opt/py/py/lib/python3.11/site-packages/jupyterlab/handlers/announcements.py", line 14, in <module>
    from jupyter_server.base.handlers import APIHandler
  File "/opt/py/py/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 23, in <module>
    from jupyter_events import EventLogger
  File "/opt/py/py/lib/python3.11/site-packages/jupyter_events/__init__.py", line 3, in <module>
    from .logger import EVENTS_METADATA_VERSION, EventLogger
  File "/opt/py/py/lib/python3.11/site-packages/jupyter_events/logger.py", line 19, in <module>
    from .schema_registry import SchemaRegistry
  File "/opt/py/py/lib/python3.11/site-packages/jupyter_events/schema_registry.py", line 3, in <module>
    from .schema import EventSchema
  File "/opt/py/py/lib/python3.11/site-packages/jupyter_events/schema.py", line 9, in <module>
    from .validators import draft7_format_checker, validate_schema
  File "/opt/py/py/lib/python3.11/site-packages/jupyter_events/validators.py", line 17, in <module>
    EVENT_METASCHEMA = yaml.load(EVENT_METASCHEMA_FILEPATH)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py/py/lib/python3.11/site-packages/jupyter_events/yaml.py", line 25, in load
    return loads(data)
           ^^^^^^^^^^^
  File "/opt/py/py/lib/python3.11/site-packages/jupyter_events/yaml.py", line 15, in loads
    return yload(stream, Loader=SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py/py/lib/python3.11/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py/py/lib/python3.11/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py/py/lib/python3.11/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/opt/py/py/lib/python3.11/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py/py/lib/python3.11/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py/py/lib/python3.11/site-packages/yaml/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Hashable'
```

I understand the issue is likely in `pyyaml`, leaving this here for visibility, feel free to close

**Comment by kevin-bates** [comment]
Hi @PhilipDeegan - this stack trace is consistent with an older version of `pyyaml` (i.e., < 5.1) yet `jupyter_events` requires `pyyaml >= 5.3`.  Could you please check your version of `pyyaml` and upgrade to at least `5.3`?

**Comment by PhilipDeegan** [comment]
I must have updated it without noticing as it's working now :+1:
