### ISSUE TITLE
Version 0.7.0 is breaking jupyter lab build

### ISSUE THREAD

**Issue by passarel** [jupyter/jupyter_events#81]
Hi

I tried to run jupyter lab build in my Ubuntu 22 container - it was working on Friday, but now it stopped working, after the release of version 0.7.0 of jupyter_events

First I had this error:

0.783 Traceback (most recent call last):
0.783   File "/opt/conda/bin/jupyter-lab", line 6, in <module>
0.783     from jupyterlab.labapp import main
0.783   File "/opt/conda/lib/python3.10/site-packages/jupyterlab/__init__.py", line 7, in <module>
0.783     from .handlers.announcements import (  # noqa
0.783   File "/opt/conda/lib/python3.10/site-packages/jupyterlab/handlers/announcements.py", line 14, in <module>
0.783     from jupyter_server.base.handlers import APIHandler
0.783   File "/opt/conda/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 23, in <module>
0.784     from jupyter_events import EventLogger
0.784   File "/opt/conda/lib/python3.10/site-packages/jupyter_events/__init__.py", line 3, in <module>
0.784     from .logger import EVENTS_METADATA_VERSION, EventLogger
0.785   File "/opt/conda/lib/python3.10/site-packages/jupyter_events/logger.py", line 18, in <module>
0.785     from .schema import SchemaType
0.785   File "/opt/conda/lib/python3.10/site-packages/jupyter_events/schema.py", line 7, in <module>
0.786     from referencing import Registry
0.786 ModuleNotFoundError: No module named 'referencing'
------

After running pip install referencing, I had the following error:

0.950 Traceback (most recent call last):
0.950   File "/opt/conda/bin/jupyter-lab", line 6, in <module>
0.950     from jupyterlab.labapp import main
0.950   File "/opt/conda/lib/python3.10/site-packages/jupyterlab/__init__.py", line 7, in <module>
0.950     from .handlers.announcements import (  # noqa
0.950   File "/opt/conda/lib/python3.10/site-packages/jupyterlab/handlers/announcements.py", line 14, in <module>
0.950     from jupyter_server.base.handlers import APIHandler
0.950   File "/opt/conda/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 23, in <module>
0.950   File "/opt/conda/lib/python3.10/site-packages/jupyter_events/__init__.py", line 3, in <module>
0.951     from .logger import EVENTS_METADATA_VERSION, EventLogger
0.951   File "/opt/conda/lib/python3.10/site-packages/jupyter_events/logger.py", line 18, in <module>
0.951     from .schema import SchemaType
0.951   File "/opt/conda/lib/python3.10/site-packages/jupyter_events/schema.py", line 18, in <module>
0.951     from .validators import draft7_format_checker, validate_schema
0.951   File "/opt/conda/lib/python3.10/site-packages/jupyter_events/validators.py", line 41, in <module>
0.951     JUPYTER_EVENTS_SCHEMA_VALIDATOR = Draft7Validator(  # type: ignore

My installation of Jupyter Lab is made on miniconda, over a nvidia-cuda container, using the following libraries:
jupyterlab==3.6.3
jupyterlab-git==0.41.0
ipywidgets==8.0.7
nb_conda_kernels==2.3.1
jupyter_contrib_nbextensions==0.7.0

After uninstalling jupyter_events 0.7.0 and reinstalling 0.6.3 the build worked fine.

**Comment by rmcd-mscb** [comment]
I have the same issue with jupyterlab 4.0.4 and 3.6.5.  Decrementing to 0.6.3 works for me as well.

**Comment by hbcarlos** [comment]
Hi @passarel and @rmcd-mscb,

Could you add a bit more context? I'm trying to reproduce it. Did you try on a clean environment?

@passarel, one thing I notice that's not related to the issue. You are talking about JupyterLab, but in the list of packages you install, you mention jupyter_contrib_nbextensions. jupyter_contrib_nbextensions is a classic Notebook set of extension and I believe it doesn't work on JupyterLab.

@passarel Are you also using the nvidia-cuda container?

**Comment by rmcd-mscb** [comment]
@Zsailer - In my case I was bulding a conda environment with the following file configuration pasted in below.  This was last week, and if you comment out the jupyter_events dependency I would hope can reproduce the error when launching jupyter lab.  I hope this helps.

name: "gdptools-examples"
channels:
  - numba
  - bokeh
  - plotly
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9,<=3.10
  - pip
  - pydantic<=1.10.9
  - gdptools==0.2.1
  - netcdf4<=1.6.0
  - jupyterlab
  - jupyter_events<0.7.0
  - jupytext
  - shapely
  - dask
  - distributed
  # HyRiver packages
  - pynhd
  - pygeoogc
  - bottleneck
  - numba
  - pyogrio
  - cartopy
  - hvplot
  - geoviews
  - holoviews
  - bokeh
  - datashader
  - networkx
  - flask
  - selenium
  - geckodriver
  - firefox
  - plotly
  - plotly-geo
  - nodejs

**Comment by Zsailer** [comment]
Thanks, @rmcd-mscb . 

I think the issue might be that we missed the `referencing` dependency in the conda recipe: https://github.com/conda-forge/jupyter_events-feedstock/pull/15. Once we make that update, I'll post back here and check if that resolved this issue.

**Comment by rmcd-mscb** [comment]
Thank you!

**Comment by Zsailer** [comment]
Let me know if you're still seeing this issue, @rmcd-mscb. 

It looks like this issue was automatically closed when we merged the changes in conda-forge. Feel free to re-open this issue if you're still seeing it.

**Comment by hbcarlos** [comment]
Thanks, @Zsailer!

**Comment by pp-mo** [comment]
Also hit this, but not fixed by recipe updates since the older builds are still there with wrong dependency information, which can cause bad environment resolution.
https://github.com/conda-forge/jupyter_events-feedstock/issues/17
