### ISSUE TITLE
`jupyter-events` break JupyterLab due to lack of `jsonschema` version pin/incompatibility with newer versions

### ISSUE THREAD

**Issue by krassowski** [jupyter/jupyter_events#99]
See:
- https://github.com/jupyter/jupyter_core/issues/369
- https://github.com/jupyterlab/jupyterlab/issues/14507#issuecomment-2188383280

But briefly:

```py
Traceback (most recent call last):
  File "/usr/bin/jupyter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/jupyter_core/command.py", line 261, in main
    mod = __import__(package)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jupyterlab/__init__.py", line 8, in <module>
    from .handlers.announcements import (
  File "/usr/lib/python3.11/site-packages/jupyterlab/handlers/announcements.py", line 14, in <module>
    from jupyter_server.base.handlers import APIHandler
  File "/usr/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 24, in <module>
    from jupyter_events import EventLogger
  File "/usr/lib/python3.11/site-packages/jupyter_events/__init__.py", line 3, in <module>
    from .logger import EVENTS_METADATA_VERSION, EventLogger
  File "/usr/lib/python3.11/site-packages/jupyter_events/logger.py", line 19, in <module>
    from .schema import SchemaType
  File "/usr/lib/python3.11/site-packages/jupyter_events/schema.py", line 18, in <module>
    from .validators import draft7_format_checker, validate_schema
  File "/usr/lib/python3.11/site-packages/jupyter_events/validators.py", line 44, in <module>
    JUPYTER_EVENTS_SCHEMA_VALIDATOR = Draft7Validator(
                                      ^^^^^^^^^^^^^^^^
TypeError: create.<locals>.Validator.__init__() got an unexpected keyword argument 'registry'
```

As per:

> Downgrading `jsonschema` from the latest `4.20.0` to `4.19.2` solved the issue for me, fyi.
> 
> _Originally posted by @gokceneraslan in https://github.com/jupyter/jupyter_core/issues/369#issuecomment-1875719805_
            
Current version is 4.22

**Comment by aktech** [comment]
Downgrading `jsonschema` to `4.19.2`, didn't work for me. Here is an example github actions run:

- `jsonschema` version: https://github.com/nebari-dev/jhub-apps/actions/runs/10680581239/job/29602328285#step:7:167
- Error Traceback: https://github.com/nebari-dev/jhub-apps/actions/runs/10680581239/job/29602328285#step:11:149

In this case it only happens when importing `CondaProject` ([ref](https://github.com/nebari-dev/jhub-apps/blob/817d746b897ee12493763f9a636263e06a1a6856/jhub_apps/service/app_from_git.py#L94)). `conda-project` depends on `conda-lock` and I suspect, when importing conda-project, it imports conda-lock dependencies and conda-locks [vendor dependencies](https://github.com/conda/conda-lock/tree/2f6a18e32668b6faf0bd356e35211e18ec1a3ea9/conda_lock/_vendor) (?) cause this behaviour.

**Comment by Orest02** [comment]
I agree, I tried all there was on Github issues and StackOverflow, none worked

**Comment by NevilleMthw** [comment]
Has this issue been resolved at all? I think there is a compatibility issue with jsonschema and jupyter_events. I have mentioned an issue as well. https://github.com/jupyter/jupyter_core/issues/407

**Comment by Zsailer** [comment]
I don't think this is due to a lack of a pin. 

I tried _many_ things to reproduce this. It's a very subtle issue, but the only way I can see this is if, after installing a Jupyter web application (e.g. Lab or Notebook), I downgrade jsonschema manually to < 4.18. This is consistent with what we'd expect given the [backward incompatible API introduced in the jsonschema package in 4.18](https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst#v4180) (and the deprecation warnings that appeared to signal this change). 

This can easily happen if users install a dependency _after_ e.g. JupyterLab that pins jsonschema. I think a lot of libraries did exactly that (pin jsonschema) when this new "registry" API was released, because it introduced a backwards incompatible change. In Jupyter, we handled this new API and updated our pin in https://github.com/jupyter/jupyter_events/pull/80.

Any version _equal or above_ jsonschema 4.18 doesn't seem to trigger this issue. 

The various threads reporting this issue are difficult to determine what version of jsonschema is running. For example, [this comment suggests it happens in a later version](https://github.com/jupyter/jupyter_core/issues/369#issuecomment-1875719805); however, they then report after downgrading and upgrading again, things worked. My hunch is that their original report of a higher version (4.20) was inaccurate.

I think the only thing we do here to improve things is add a version check on jsonschema when jupyter_events is imported and raise an error forcing users to upgrade jsonschema. This might cause conflicts with packages that pin jsonschema, but such is life in the Python work 😅. At least, this would be a more clear error.

**Comment by krassowski** [comment]
Thank you for looking into this!
